# -*- coding: utf-8 -*-
"""nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yb7PkadvMTsvyvtA1OecSC8b6VkHZYO9
"""

from IPython.display import display, HTML

display(HTML("""<!DOCTYPE html>
<html lang="hi">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Hindi Ambiguity Resolver</title>
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: 'Segoe UI', Arial, sans-serif;
  background: #f0f6ff;
  color: #0a1628;
  min-height: 100vh;
  padding: 28px 16px 60px;
}
.app { max-width: 800px; margin: 0 auto; }
.hdr { margin-bottom: 28px; text-align: center; }
.hdr h1 { font-size: 28px; font-weight: 700; color: #1a4fa0; letter-spacing: -0.5px; }
.hdr h1 span { color: #2979ff; }
.hdr-sub { font-size: 13px; color: #5a7ab5; margin-top: 6px; letter-spacing: .03em; }
.stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin-bottom: 22px; }
.stat { background: #fff; border: 1.5px solid #c3d9ff; border-radius: 12px; padding: 14px 10px; text-align: center; box-shadow: 0 1px 4px rgba(41,121,255,0.07); }
.stat .val { font-size: 22px; font-weight: 700; color: #2979ff; }
.stat .lbl { font-size: 10px; color: #7a9cc7; margin-top: 3px; letter-spacing: .05em; text-transform: uppercase; }
.filters { display: flex; gap: 6px; flex-wrap: wrap; margin-bottom: 18px; }
.fchip { font-size: 11px; padding: 5px 14px; border-radius: 99px; cursor: pointer; border: 1.5px solid #b3ccf5; color: #4a6fa5; background: #fff; font-family: inherit; letter-spacing: .03em; transition: all .15s; }
.fchip:hover { border-color: #2979ff; color: #2979ff; background: #eaf1ff; }
.fchip.active { background: #2979ff; color: #fff; border-color: #2979ff; font-weight: 600; }
.fchip.f-lexical.active { background: #0288d1; border-color: #0288d1; }
.fchip.f-syntactic.active { background: #1565c0; border-color: #1565c0; }
.fchip.f-semantic.active { background: #0277bd; border-color: #0277bd; }
.fchip.f-pragmatic.active { background: #1976d2; border-color: #1976d2; }
.fchip.f-idiomatic.active { background: #283593; border-color: #283593; }
.fchip.f-referential.active { background: #0097a7; border-color: #0097a7; }
.search-card { background: #fff; border: 1.5px solid #c3d9ff; border-radius: 16px; padding: 18px 18px 14px; box-shadow: 0 2px 10px rgba(41,121,255,0.08); margin-bottom: 18px; }
.search-label { font-size: 12px; color: #5a7ab5; font-weight: 600; letter-spacing: .06em; text-transform: uppercase; margin-bottom: 10px; }
.input-row { display: flex; gap: 8px; align-items: center; margin-bottom: 10px; }
.input-row input { flex: 1; padding: 12px 16px; font-size: 16px; border: 1.5px solid #b3ccf5; border-radius: 10px; background: #f5f9ff; color: #0a1628; outline: none; font-family: inherit; transition: border-color .15s; }
.input-row input:focus { border-color: #2979ff; background: #fff; }
.input-row input::placeholder { color: #a0b8d8; font-size: 14px; }
.btn-search { padding: 12px 20px; background: #2979ff; color: #fff; border: none; border-radius: 10px; font-size: 14px; font-weight: 600; cursor: pointer; white-space: nowrap; font-family: inherit; transition: background .15s; }
.btn-search:hover { background: #1a5fd4; }
.btn-search:active { transform: scale(0.97); }
.btn-clear { padding: 12px 16px; background: #fff; color: #e53935; border: 1.5px solid #ffcdd2; border-radius: 10px; font-size: 13px; font-weight: 600; cursor: pointer; white-space: nowrap; font-family: inherit; transition: all .15s; }
.btn-clear:hover { background: #ffebee; border-color: #e53935; }
.btn-clear:active { transform: scale(0.97); }
.hint-row { font-size: 11px; color: #7a9cc7; margin-bottom: 10px; display: flex; align-items: center; gap: 6px; flex-wrap: wrap; }
.hint-tag { background: #eaf1ff; color: #2979ff; border-radius: 6px; padding: 2px 8px; font-size: 11px; font-weight: 600; }
.chips-label { font-size: 10px; color: #7a9cc7; letter-spacing: .08em; text-transform: uppercase; margin-bottom: 7px; }
.chips { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 22px; }
.chip { font-size: 12px; padding: 5px 12px; border-radius: 8px; cursor: pointer; border: 1.5px solid #c3d9ff; color: #3a6ab5; background: #fff; transition: all .15s; font-family: inherit; }
.chip:hover { border-color: #2979ff; color: #2979ff; background: #eaf1ff; }
.chip.hinglish { border-style: dashed; color: #0288d1; }
.chip.hinglish:hover { background: #e1f5fe; border-color: #0288d1; }
.rcard { background: #fff; border: 1.5px solid #b3ccf5; border-radius: 16px; overflow: hidden; margin-bottom: 12px; box-shadow: 0 2px 12px rgba(41,121,255,0.08); animation: fadeIn .2s ease; }
@keyframes fadeIn { from { opacity: 0; transform: translateY(6px); } to { opacity: 1; transform: translateY(0); } }
.rcard-hdr { padding: 14px 18px; background: linear-gradient(90deg, #eaf1ff 0%, #f5f9ff 100%); border-bottom: 1.5px solid #c3d9ff; display: flex; align-items: flex-start; justify-content: space-between; gap: 10px; flex-wrap: wrap; }
.rcard-hdr .sent { font-size: 19px; font-weight: 700; color: #1a4fa0; flex: 1; line-height: 1.35; }
.type-pill { font-size: 10px; padding: 3px 11px; border-radius: 99px; white-space: nowrap; flex-shrink: 0; margin-top: 4px; font-weight: 600; letter-spacing: .04em; }
.tp-lexical { background: #e1f5fe; color: #0277bd; }
.tp-syntactic { background: #e8eaf6; color: #283593; }
.tp-semantic { background: #e3f2fd; color: #1565c0; }
.tp-pragmatic { background: #e1f5fe; color: #0288d1; }
.tp-idiomatic { background: #e8f5e9; color: #1b5e20; }
.tp-referential { background: #e0f7fa; color: #006064; }
.meanings-grid { display: grid; grid-template-columns: 1fr 1fr; }
.meaning { padding: 15px 18px; background: #fff; }
.meaning:first-child { border-right: 1.5px solid #e3eeff; }
.meaning:nth-child(3) { border-top: 1.5px solid #e3eeff; }
.meaning:nth-child(4) { border-top: 1.5px solid #e3eeff; border-left: 1.5px solid #e3eeff; }
.mlabel { font-size: 9px; font-weight: 700; letter-spacing: .1em; text-transform: uppercase; margin-bottom: 8px; display: flex; align-items: center; gap: 6px; }
.mlabel::before { content: ''; display: inline-block; width: 18px; height: 2px; border-radius: 2px; }
.m1 .mlabel { color: #1976d2; }
.m1 .mlabel::before { background: #2979ff; }
.m2 .mlabel { color: #0288d1; }
.m2 .mlabel::before { background: #0288d1; }
.m3 .mlabel { color: #283593; }
.m3 .mlabel::before { background: #283593; }
.m4 .mlabel { color: #0097a7; }
.m4 .mlabel::before { background: #0097a7; }
.mhi { font-size: 16px; color: #0a1628; line-height: 1.55; margin-bottom: 5px; font-weight: 500; }
.men { font-size: 12px; color: #5a7ab5; line-height: 1.5; font-style: italic; }
.example-tag { padding: 9px 18px; border-top: 1.5px solid #e3eeff; font-size: 12px; color: #7a9cc7; background: #f8fbff; }
.sec-label { font-size: 10px; letter-spacing: .1em; color: #7a9cc7; text-transform: uppercase; margin-bottom: 10px; }
.browse-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(185px, 1fr)); gap: 8px; }
.browse-card { background: #fff; border: 1.5px solid #c3d9ff; border-radius: 12px; padding: 12px 14px; cursor: pointer; transition: all .15s; box-shadow: 0 1px 3px rgba(41,121,255,0.05); }
.browse-card:hover { border-color: #2979ff; background: #eaf1ff; transform: translateY(-1px); }
.browse-card .bkey { font-size: 14px; color: #1a4fa0; font-weight: 600; margin-bottom: 4px; line-height: 1.4; }
.browse-card .btype { font-size: 10px; color: #7a9cc7; letter-spacing: .04em; }
.notfound { background: #fff3e0; border: 1.5px solid #ffe0b2; border-radius: 12px; padding: 16px 18px; color: #e65100; font-size: 14px; line-height: 1.7; }
.notfound strong { color: #bf360c; }
.mode-row { display: flex; gap: 8px; margin-bottom: 12px; align-items: center; }
.mode-label { font-size: 11px; color: #5a7ab5; font-weight: 600; margin-right: 4px; }
.mode-btn { font-size: 11px; padding: 4px 14px; border-radius: 99px; cursor: pointer; border: 1.5px solid #b3ccf5; color: #5a7ab5; background: #fff; font-family: inherit; font-weight: 500; transition: all .15s; }
.mode-btn.active { background: #2979ff; color: #fff; border-color: #2979ff; }
.mode-btn:hover:not(.active) { border-color: #2979ff; color: #2979ff; }
@media (max-width: 520px) {
  .meanings-grid { grid-template-columns: 1fr; }
  .meaning:first-child { border-right: none; border-bottom: 1.5px solid #e3eeff; }
  .meaning:nth-child(3) { border-left: none; }
  .stats { grid-template-columns: repeat(2, 1fr); }
}
</style>
</head>
<body>
<div class="app">
  <div class="hdr">
    <h1>Hindi <span>Ambiguity</span> Resolver</h1>
    <div class="hdr-sub">हिंदी और Hinglish में टाइप करें — शब्द, वाक्य, मुहावरे</div>
  </div>
  <div class="stats">
    <div class="stat"><div class="val" id="s-total">60</div><div class="lbl">entries</div></div>
    <div class="stat"><div class="val" id="s-filtered">60</div><div class="lbl">showing</div></div>
    <div class="stat"><div class="val">6</div><div class="lbl">types</div></div>
    <div class="stat"><div class="val">2-4</div><div class="lbl">meanings</div></div>
  </div>
  <div class="filters" id="filterBar"></div>
  <div class="search-card">
    <div class="search-label">Search in Hindi or Hinglish</div>
    <div class="mode-row">
      <span class="mode-label">Input mode:</span>
      <button class="mode-btn active" id="modeHindi" onclick="setMode('hindi')">हिंदी Hindi</button>
      <button class="mode-btn" id="modeHinglish" onclick="setMode('hinglish')">Hinglish (Roman)</button>
    </div>
    <div class="hint-row" id="hintRow" style="display:none">
      <span>Hinglish examples:</span>
      <span class="hint-tag">kal</span>
      <span class="hint-tag">sona</span>
      <span class="hint-tag">dil toot gaya</span>
      <span class="hint-tag">bank gaya</span>
      <span class="hint-tag">aankhein khul gayin</span>
      <span class="hint-tag">bahut acha</span>
    </div>
    <div class="input-row">
      <input type="text" id="searchInp" placeholder="हिंदी वाक्य या शब्द टाइप करें..." />
      <button class="btn-search" onclick="doSearch()">खोजें</button>
      <button class="btn-clear" onclick="clearAll()">&#10005; Clear</button>
    </div>
  </div>
  <div class="chips-label">Quick examples — click to search</div>
  <div class="chips" id="quickChips"></div>
  <div class="sec-label" id="browseLabel">Browse all entries</div>
  <div id="mainOut"></div>
</div>

<script>
const HINGLISH_MAP = {
  "kal":"कल","sona":"सोना","gold":"सोना","neend":"सोना",
  "patra":"पत्र","letter":"पत्र","patta":"पत्र","leaf":"पत्र",
  "bank":"बैंक","arth":"अर्थ","matlab":"अर्थ","meaning":"अर्थ","dhan":"अर्थ",
  "kul":"कुल","total":"कुल","vansh":"कुल",
  "aam":"आम","mango":"आम","common":"आम",
  "haar":"हार","defeat":"हार","mala":"हार","necklace":"हार",
  "jal":"जल","paani":"जल","water":"जल",
  "kar":"कर","tax":"कर",
  "phal":"फल","fruit":"फल","result":"फल",
  "man":"मन","mind":"मन",
  "kaal":"काल","time":"काल","death":"काल",
  "raj":"राज","kingdom":"राज","secret":"राज",
  "par":"पर","but":"पर","wing":"पर",
  "nav":"नव","new":"नव","nine":"नव",
  "shakti":"शक्ति","power":"शक्ति","strength":"शक्ति",
  "soor":"सूर","sur":"सूर","sun":"सूर",
  "safar":"सफर","journey":"सफर","travel":"सफर",
  "neta":"नेता","leader":"नेता","politician":"नेता",
  "mujhe sona chahiye":"मुझे सोना चाहिए",
  "i need sleep":"मुझे सोना चाहिए",
  "i need gold":"मुझे सोना चाहिए",
  "woh bank gaya":"वह बैंक गया",
  "bank gaya":"वह बैंक गया",
  "he went to bank":"वह बैंक गया",
  "patra gir gaya":"पत्र गिर गया",
  "letter fell":"पत्र गिर गया",
  "leaf fell":"पत्र गिर गया",
  "woh kal aayega":"वह कल आएगा",
  "he will come tomorrow":"वह कल आएगा",
  "mera phone mar gaya":"मेरा फोन मर गया",
  "my phone died":"मेरा फोन मर गया",
  "aam aadmi":"आम आदमी",
  "common man":"आम आदमी",
  "dil toot gaya":"दिल टूट गया",
  "heartbreak":"दिल टूट गया",
  "heart broke":"दिल टूट गया",
  "aankhein khul gayin":"उसकी आँखें खुल गईं",
  "eyes opened":"उसकी आँखें खुल गईं",
  "sitting idle":"हाथ पर हाथ धरे बैठा है",
  "doing nothing":"हाथ पर हाथ धरे बैठा है",
  "naak kat gayi":"नाक कट गई",
  "lost honour":"नाक कट गई",
  "fell in love":"आँखें चार हो गईं",
  "eyes met":"आँखें चार हो गईं",
  "mouth watered":"मुँह में पानी आ गया",
  "betrayal":"पीठ में छुरा घोंपना",
  "stabbed in back":"पीठ में छुरा घोंपना",
  "badly defeated":"दाँत खट्टे हो गए",
  "can you close the door":"क्या आप दरवाजा बंद कर सकते हैं",
  "it is very cold here":"यहाँ बहुत ठंड है",
  "everything is fine":"सब कुछ ठीक है",
  "sab kuch theek hai":"सब कुछ ठीक है",
  "you are very smart":"तुम बहुत होशियार हो",
  "bahut acha":"बहुत अच्छा!",
  "bahut achha":"बहुत अच्छा!",
  "very good":"बहुत अच्छा!",
  "is this necessary":"क्या यह जरूरी है",
  "he got into trouble":"वह पानी में उतर गया",
  "his face fell":"उसका चेहरा उतर गया",
  "work is done":"काम खत्म हो गया",
  "he kept quiet":"उसने मुँह बंद रखा",
  "mohan said ram is sick":"मोहन ने राम से कहा कि वह बीमार है",
  "withdrew support":"उसने हाथ खींच लिया",
  "troubled a lot":"नाक में दम कर दिया",
  "work is over":"काम तमाम हो गया"
};

const DB = [
  {key:"कल",type:"lexical",meanings:[{hi:"बीता हुआ दिन",en:"Yesterday — the day that has passed"},{hi:"आने वाला दिन",en:"Tomorrow — the day yet to come"}],example:"Hinglish: kal"},
  {key:"सोना",type:"lexical",meanings:[{hi:"नींद लेना",en:"To sleep — the act of resting"},{hi:"स्वर्ण धातु",en:"Gold — the precious yellow metal"}],example:"Hinglish: sona, gold"},
  {key:"पत्र",type:"lexical",meanings:[{hi:"चिट्ठी / पत्र",en:"A letter — written correspondence"},{hi:"पेड़ का पत्ता",en:"A leaf — part of a plant or tree"}],example:"Hinglish: patra, letter, leaf"},
  {key:"बैंक",type:"lexical",meanings:[{hi:"वित्तीय संस्थान",en:"A financial institution"},{hi:"नदी का किनारा",en:"The bank / shore of a river"}],example:"Hinglish: bank"},
  {key:"अर्थ",type:"lexical",meanings:[{hi:"मतलब / अभिप्राय",en:"Meaning — the sense of a word"},{hi:"धन / संपत्ति",en:"Wealth / money — financial resources"}],example:"Hinglish: arth, meaning"},
  {key:"कुल",type:"lexical",meanings:[{hi:"सब मिलाकर / कुल योग",en:"Total — the sum of all things"},{hi:"वंश / परिवार",en:"Lineage / family clan"}],example:"Hinglish: kul, total"},
  {key:"आम",type:"lexical",meanings:[{hi:"साधारण / सामान्य",en:"Common / ordinary / usual"},{hi:"आम का फल",en:"Mango — the tropical fruit"}],example:"Hinglish: aam, mango"},
  {key:"हार",type:"lexical",meanings:[{hi:"पराजय / हार जाना",en:"Defeat — losing a contest"},{hi:"गले का हार (आभूषण)",en:"A garland or necklace"}],example:"Hinglish: haar, defeat"},
  {key:"जल",type:"lexical",meanings:[{hi:"पानी",en:"Water — the liquid"},{hi:"जलना / जलाना",en:"To burn — fire-related"}],example:"Hinglish: jal, water"},
  {key:"कर",type:"lexical",meanings:[{hi:"टैक्स / कर (tax)",en:"Tax — money paid to government"},{hi:"हाथ / करना (do)",en:"Hand / to do something"}],example:"Hinglish: kar, tax"},
  {key:"फल",type:"lexical",meanings:[{hi:"खाने का फल",en:"Fruit — edible produce of a plant"},{hi:"परिणाम / नतीजा",en:"Result / outcome / consequence"}],example:"Hinglish: phal, fruit, result"},
  {key:"मन",type:"lexical",meanings:[{hi:"मस्तिष्क / हृदय (mind)",en:"Mind — the thinking faculty"},{hi:"वजन की इकाई (40 kg)",en:"Maund — a unit of weight"}],example:"Hinglish: man, mind"},
  {key:"काल",type:"lexical",meanings:[{hi:"समय / युग",en:"Time / era / period"},{hi:"मृत्यु / यमराज",en:"Death / the god of death (Yama)"}],example:"Hinglish: kaal, time, death"},
  {key:"राज",type:"lexical",meanings:[{hi:"राज्य / शासन",en:"Kingdom / rule / governance"},{hi:"रहस्य / भेद",en:"Secret / mystery"}],example:"Hinglish: raj, secret, kingdom"},
  {key:"पर",type:"lexical",meanings:[{hi:"लेकिन / परंतु",en:"But / however — a conjunction"},{hi:"पंख (wing)",en:"Wing — a bird's appendage"},{hi:"ऊपर / पर (on/upon)",en:"On / upon — a preposition"}],example:"Hinglish: par, but, wing"},
  {key:"नव",type:"lexical",meanings:[{hi:"नया / नवीन",en:"New / fresh / novel"},{hi:"नौ (संख्या 9)",en:"Nine — the number 9"}],example:"Hinglish: nav, new, nine"},
  {key:"शक्ति",type:"lexical",meanings:[{hi:"ताकत / बल",en:"Physical strength or power"},{hi:"देवी शक्ति / दुर्गा",en:"Goddess Shakti / divine energy"}],example:"Hinglish: shakti, power"},
  {key:"सूर",type:"lexical",meanings:[{hi:"सूरज / सूर्य",en:"The sun"},{hi:"वीर / बहादुर",en:"Brave / heroic person"},{hi:"अंधा (sightless)",en:"Blind — without sight"}],example:"Hinglish: soor, sur, sun"},
  {key:"सफर",type:"lexical",meanings:[{hi:"यात्रा / भ्रमण",en:"A physical journey or travel"},{hi:"जीवन का अनुभव",en:"The journey of life (metaphorical)"}],example:"Hinglish: safar, journey"},
  {key:"नेता",type:"lexical",meanings:[{hi:"राजनीतिक नेता",en:"A political leader or politician"},{hi:"किसी समूह का अगुवा",en:"Leader of any group or movement"}],example:"Hinglish: neta, leader"},
  {key:"मुझे सोना चाहिए",type:"lexical",meanings:[{hi:"मुझे नींद लेनी है",en:"I need to sleep — I am tired"},{hi:"मुझे स्वर्ण धातु चाहिए",en:"I want gold — the precious metal"}],example:"Hinglish: mujhe sona chahiye"},
  {key:"वह बैंक गया",type:"lexical",meanings:[{hi:"वह वित्तीय संस्थान में गया",en:"He went to the financial bank"},{hi:"वह नदी के किनारे गया",en:"He went to the river bank / shore"}],example:"Hinglish: woh bank gaya / bank gaya"},
  {key:"पत्र गिर गया",type:"lexical",meanings:[{hi:"चिट्ठी जमीन पर गिर गई",en:"The letter fell to the ground"},{hi:"पेड़ का पत्ता नीचे गिर गया",en:"The leaf fell down from the tree"}],example:"Hinglish: patra gir gaya / letter fell"},
  {key:"वह कल आएगा",type:"lexical",meanings:[{hi:"वह आने वाले दिन आएगा",en:"He will come tomorrow"},{hi:"वह बीते दिन आया था",en:"He came yesterday (misread tense)"}],example:"Hinglish: woh kal aayega"},
  {key:"मेरा फोन मर गया",type:"lexical",meanings:[{hi:"मेरे फोन की बैटरी खत्म हो गई",en:"My phone battery completely died"},{hi:"मेरा फोन स्थायी रूप से खराब हो गया",en:"My phone permanently stopped working"}],example:"Hinglish: mera phone mar gaya"},
  {key:"आम आदमी",type:"lexical",meanings:[{hi:"साधारण / सामान्य व्यक्ति",en:"A common / ordinary person"},{hi:"राजनीतिक दल का नाम (AAP)",en:"A political party name (Aam Aadmi Party)"}],example:"Hinglish: aam aadmi / common man"},
  {key:"उसका हाथ तंग है",type:"lexical",meanings:[{hi:"उसका हाथ शारीरिक रूप से तंग है",en:"His hand is physically tight / injured"},{hi:"वह आर्थिक रूप से तंगहाल है",en:"He is financially struggling / broke"}],example:"Hinglish: uska haath tang hai"},
  {key:"मैंने दूरबीन से आदमी को देखा",type:"syntactic",meanings:[{hi:"मैंने दूरबीन का उपयोग करके आदमी देखा",en:"I saw the man using binoculars (I had them)"},{hi:"मैंने उस आदमी को देखा जिसके पास दूरबीन थी",en:"I saw the man who had binoculars (he had them)"}],example:"Instrumental phrase attachment ambiguity"},
  {key:"लड़की ने टोपी वाले लड़के को बुलाया",type:"syntactic",meanings:[{hi:"लड़की ने उस लड़के को बुलाया जो टोपी पहने था",en:"The girl called the boy who was wearing a cap"},{hi:"टोपी वाली लड़की ने लड़के को बुलाया",en:"The girl with the cap called the boy"}],example:"Modifier attachment — who wears the cap?"},
  {key:"बच्चों को पढ़ाने वाले शिक्षक आए",type:"syntactic",meanings:[{hi:"वे शिक्षक आए जो बच्चों को पढ़ाते हैं",en:"The teachers who teach children came"},{hi:"शिक्षक बच्चों को पढ़ाने के उद्देश्य से आए",en:"The teachers came for the purpose of teaching children"}],example:"Relative clause vs purpose clause"},
  {key:"सुंदर लड़कियों और लड़कों का मेला",type:"syntactic",meanings:[{hi:"सुंदर लड़कियाँ और (सभी) लड़के",en:"Beautiful girls and all boys — adjective only on girls"},{hi:"सुंदर लड़कियाँ और सुंदर लड़के",en:"Beautiful girls and beautiful boys — adjective on both"}],example:"Adjective scope ambiguity"},
  {key:"मैंने देखा रोता हुआ बच्चा और माँ",type:"syntactic",meanings:[{hi:"मैंने रोते हुए बच्चे और माँ को देखा",en:"I saw the crying child and the mother"},{hi:"मैंने बच्चे और रोती हुई माँ को देखा",en:"I saw the child and the crying mother"}],example:"Participial phrase attachment ambiguity"},
  {key:"बैंक में पैसे रखो",type:"semantic",meanings:[{hi:"वित्तीय संस्थान में धन जमा करो",en:"Deposit money in the financial bank"},{hi:"नदी किनारे पैसे रखो (असामान्य)",en:"Place money on the river bank (unusual)"}],example:"Hinglish: bank mein paise rakho"},
  {key:"वह घर में घुस गया",type:"semantic",meanings:[{hi:"वह अपने घर के अंदर चला गया",en:"He entered his own house"},{hi:"वह बिना अनुमति किसी के घर में दाखिल हुआ",en:"He trespassed into someone's house"}],example:"Intent changes the legal interpretation"},
  {key:"उसने मुँह बंद रखा",type:"semantic",meanings:[{hi:"उसने शारीरिक रूप से मुँह बंद रखा",en:"He kept his mouth physically closed"},{hi:"उसने कुछ नहीं बोला / चुप रहा",en:"He stayed silent and said nothing"}],example:"Literal vs idiomatic silence"},
  {key:"वह पानी में उतर गया",type:"semantic",meanings:[{hi:"वह नदी या तालाब में प्रवेश कर गया",en:"He entered a river or pond (literal)"},{hi:"वह किसी मुसीबत में फँस गया",en:"He got into trouble / a difficult situation"}],example:"Hinglish: he got into trouble"},
  {key:"उसका चेहरा उतर गया",type:"semantic",meanings:[{hi:"उसके चेहरे का रंग फीका पड़ गया",en:"The colour drained from his face (sadness)"},{hi:"उसका मुखौटा उतर गया और असली चेहरा दिखा",en:"His mask came off — his true self was revealed"}],example:"Hinglish: his face fell"},
  {key:"काम खत्म हो गया",type:"semantic",meanings:[{hi:"कार्य सफलतापूर्वक पूर्ण हो गया",en:"The work was successfully completed"},{hi:"यह काम बर्बाद / नष्ट हो गया",en:"This work was ruined or destroyed"}],example:"Completion vs destruction reading"},
  {key:"क्या आप दरवाजा बंद कर सकते हैं",type:"pragmatic",meanings:[{hi:"क्या आपमें दरवाजा बंद करने की क्षमता है?",en:"Are you capable of closing the door? (literal)"},{hi:"कृपया दरवाजा बंद करें (विनम्र अनुरोध)",en:"Please close the door (polite indirect request)"}],example:"Hinglish: can you close the door"},
  {key:"यहाँ बहुत ठंड है",type:"pragmatic",meanings:[{hi:"मौसम ठंडा होने का एक तथ्य",en:"A factual observation — it is cold here"},{hi:"खिड़की या दरवाजा बंद करने का संकेत",en:"An indirect request to close the window or door"}],example:"Hinglish: it is very cold here"},
  {key:"सब कुछ ठीक है",type:"pragmatic",meanings:[{hi:"सभी चीजें वास्तव में अच्छी अवस्था में हैं",en:"Everything is genuinely fine"},{hi:"मैं इस विषय पर बात नहीं करना चाहता",en:"I do not want to discuss this (evasive response)"}],example:"Hinglish: sab kuch theek hai / everything is fine"},
  {key:"क्या तुम खाना खाओगे",type:"pragmatic",meanings:[{hi:"तुमसे खाने के बारे में वास्तविक प्रश्न",en:"A genuine question about whether you will eat"},{hi:"खाना खाने का निमंत्रण / आग्रह",en:"An invitation or insistence to eat"}],example:"Question vs invitation"},
  {key:"तुम बहुत होशियार हो",type:"pragmatic",meanings:[{hi:"तुम वाकई बहुत बुद्धिमान हो (प्रशंसा)",en:"You are genuinely very smart (sincere compliment)"},{hi:"तुमने चालाकी की — व्यंग्य (sarcasm)",en:"You are being cunning — sarcastic criticism"}],example:"Hinglish: you are very smart"},
  {key:"बहुत अच्छा!",type:"pragmatic",meanings:[{hi:"वाकई बहुत अच्छा — सच्ची प्रशंसा",en:"Truly very good — genuine praise"},{hi:"व्यंग्यात्मक — बिल्कुल भी अच्छा नहीं",en:"Sarcastic — not good at all (irony)"}],example:"Hinglish: bahut acha / very good"},
  {key:"क्या यह जरूरी है",type:"pragmatic",meanings:[{hi:"सच में जानना चाहते हैं कि यह आवश्यक है?",en:"Genuinely asking if this is necessary"},{hi:"यह जरूरी नहीं है — व्यंग्यात्मक प्रश्न",en:"Rhetorical — implying it is NOT necessary"}],example:"Hinglish: is this necessary"},
  {key:"दिल टूट गया",type:"idiomatic",meanings:[{hi:"हृदय को शारीरिक क्षति हुई",en:"The heart was physically broken (literal)"},{hi:"भावनात्मक रूप से गहरा दुख हुआ",en:"Deep emotional pain — heartbreak (figurative)"}],example:"Hinglish: dil toot gaya / heartbreak"},
  {key:"उसकी आँखें खुल गईं",type:"idiomatic",meanings:[{hi:"वह नींद से जाग गया",en:"He/she woke up from sleep (literal)"},{hi:"उसे वास्तविकता का बोध हो गया",en:"He/she realized the truth / had a revelation"}],example:"Hinglish: aankhein khul gayin / eyes opened"},
  {key:"हाथ पर हाथ धरे बैठा है",type:"idiomatic",meanings:[{hi:"वह शारीरिक रूप से हाथ रखे बैठा है",en:"Literally sitting with hands placed on hands"},{hi:"वह बिना कुछ किए आलसी बैठा है",en:"Sitting idle, doing absolutely nothing"}],example:"Hinglish: sitting idle / doing nothing"},
  {key:"नाक कट गई",type:"idiomatic",meanings:[{hi:"नाक की शारीरिक क्षति हुई",en:"The nose was physically cut (literal)"},{hi:"इज्जत / मान-सम्मान चला गया",en:"One lost their honour and reputation"}],example:"Hinglish: naak kat gayi / lost honour"},
  {key:"नाक में दम कर दिया",type:"idiomatic",meanings:[{hi:"नाक में शारीरिक रुकावट हुई",en:"Something literally blocked the nose"},{hi:"बहुत परेशान कर दिया",en:"Made life very difficult / troubled greatly"}],example:"Hinglish: troubled a lot"},
  {key:"काम तमाम हो गया",type:"idiomatic",meanings:[{hi:"कार्य पूर्ण हो गया",en:"The work / task is completely finished"},{hi:"किसी की मृत्यु या बर्बादी हुई",en:"Someone was finished off / killed (euphemism)"}],example:"Hinglish: kaam tamaam ho gaya / work is over"},
  {key:"आँखें चार हो गईं",type:"idiomatic",meanings:[{hi:"चार आँखें शारीरिक रूप से मिलीं",en:"Four eyes literally met (strange literal reading)"},{hi:"दो लोग पहली बार मिले / प्रेम हुआ",en:"Two people met / fell in love (idiom)"}],example:"Hinglish: aankhein chaar ho gayin / fell in love"},
  {key:"मुँह में पानी आ गया",type:"idiomatic",meanings:[{hi:"मुँह में शारीरिक रूप से पानी भर आया",en:"Water literally filled in the mouth"},{hi:"भोजन देखकर खाने की इच्छा हुई",en:"The mouth watered — craving food"}],example:"Hinglish: mouth watered"},
  {key:"पीठ में छुरा घोंपना",type:"idiomatic",meanings:[{hi:"किसी की पीठ में शारीरिक रूप से छुरा मारना",en:"Literally stabbing someone in the back"},{hi:"विश्वासघात करना / धोखा देना",en:"Betrayal — stabbing in the back (figurative)"}],example:"Hinglish: betrayal / stabbed in back"},
  {key:"उसने हाथ खींच लिया",type:"idiomatic",meanings:[{hi:"उसने शारीरिक रूप से हाथ पीछे किया",en:"He physically pulled his hand back"},{hi:"उसने समर्थन / सहयोग वापस ले लिया",en:"He withdrew his support or cooperation"}],example:"Hinglish: withdrew support"},
  {key:"दाँत खट्टे हो गए",type:"idiomatic",meanings:[{hi:"दाँतों में खट्टापन महसूस हुआ",en:"The teeth literally felt sour"},{hi:"बुरी तरह हार गया / मात खाई",en:"Was badly defeated — got a taste of defeat"}],example:"Hinglish: badly defeated"},
  {key:"राम ने श्याम को उसकी किताब दी",type:"referential",meanings:[{hi:"राम ने राम की किताब श्याम को दी",en:"Ram gave Ram's own book to Shyam"},{hi:"राम ने श्याम की किताब वापस श्याम को दी",en:"Ram returned Shyam's book to Shyam"}],example:"उसकी is ambiguous — whose book?"},
  {key:"मोहन ने राम से कहा कि वह बीमार है",type:"referential",meanings:[{hi:"मोहन ने कहा कि मोहन स्वयं बीमार है",en:"Mohan said that Mohan himself is sick"},{hi:"मोहन ने कहा कि राम बीमार है",en:"Mohan said that Ram is sick"}],example:"Pronoun वह — which person?"},
  {key:"वह किताब टेबल पर है जो मैंने पढ़ी",type:"referential",meanings:[{hi:"मैंने जो किताब पढ़ी वह टेबल पर रखी है",en:"The book that I read is on the table"},{hi:"जो किताब टेबल पर है उसे मैंने पढ़ा",en:"The book on the table is one I have read"}],example:"Relative clause referent ambiguity"},
  {key:"सीता ने गीता से कहा कि उसके पति आए हैं",type:"referential",meanings:[{hi:"सीता ने कहा कि सीता के पति आए हैं",en:"Sita said that Sita's husband has come"},{hi:"सीता ने कहा कि गीता के पति आए हैं",en:"Sita told Geeta that Geeta's husband has come"}],example:"Classic pronoun reference ambiguity"},
  {key:"उसने अपनी माँ को उसकी बात बताई",type:"referential",meanings:[{hi:"उसने अपनी माँ को उसी की बात बताई",en:"He told his mother about his own matter"},{hi:"उसने अपनी माँ को किसी और की बात बताई",en:"He told his mother about someone else's matter"}],example:"Three-way pronoun ambiguity"},
  {key:"जब राम आया तो उसने खाना खाया",type:"referential",meanings:[{hi:"जब राम आया तो राम ने खाना खाया",en:"When Ram came, Ram ate the food"},{hi:"जब राम आया तो किसी और ने खाना खाया",en:"When Ram came, someone else ate the food"}],example:"Subject of eating is ambiguous"}
];

const TYPE_META = {
  lexical:     {label:"शाब्दिक",     en:"Lexical"},
  syntactic:   {label:"वाक्यरचना",   en:"Syntactic"},
  semantic:    {label:"अर्थात्मक",   en:"Semantic"},
  pragmatic:   {label:"व्यावहारिक",  en:"Pragmatic"},
  idiomatic:   {label:"मुहावरा",     en:"Idiomatic"},
  referential: {label:"संदर्भात्मक", en:"Referential"}
};
const MCLASS = ["m1","m2","m3","m4"];
let activeFilter = null, searchQuery = "", inputMode = "hindi";

function setMode(mode) {
  inputMode = mode;
  const inp = document.getElementById("searchInp");
  const hint = document.getElementById("hintRow");
  document.getElementById("modeHindi").classList.toggle("active", mode === "hindi");
  document.getElementById("modeHinglish").classList.toggle("active", mode === "hinglish");
  inp.placeholder = mode === "hinglish" ? "Type in Roman e.g. dil toot gaya, kal, sona..." : "हिंदी वाक्य या शब्द टाइप करें...";
  hint.style.display = mode === "hinglish" ? "flex" : "none";
  buildChips();
  inp.focus();
}

function resolveHinglish(q) {
  const lower = q.toLowerCase().trim();
  if (HINGLISH_MAP[lower]) return HINGLISH_MAP[lower];
  for (const [hgl, hindi] of Object.entries(HINGLISH_MAP)) {
    if (lower.includes(hgl) || hgl.includes(lower)) return hindi;
  }
  return null;
}

function buildFilters() {
  const bar = document.getElementById("filterBar");
  bar.innerHTML = "";
  const all = document.createElement("button");
  all.className = "fchip active"; all.textContent = "सभी / All";
  all.onclick = () => setFilter(null, all);
  bar.appendChild(all);
  for (const [k, v] of Object.entries(TYPE_META)) {
    const b = document.createElement("button");
    b.className = "fchip f-" + k;
    b.textContent = v.label + " / " + v.en;
    b.onclick = () => setFilter(k, b);
    bar.appendChild(b);
  }
}

function setFilter(type, el) {
  activeFilter = type;
  document.querySelectorAll(".fchip").forEach(b => b.classList.remove("active"));
  el.classList.add("active");
  searchQuery = "";
  document.getElementById("searchInp").value = "";
  render();
}

const QUICK_H = {
  hindi: [
    {label:"मुझे सोना चाहिए",val:"मुझे सोना चाहिए"},
    {label:"वह बैंक गया",val:"वह बैंक गया"},
    {label:"दिल टूट गया",val:"दिल टूट गया"},
    {label:"कल",val:"कल"},
    {label:"आम",val:"आम"},
    {label:"दाँत खट्टे हो गए",val:"दाँत खट्टे हो गए"},
    {label:"बहुत अच्छा!",val:"बहुत अच्छा!"},
    {label:"आँखें चार हो गईं",val:"आँखें चार हो गईं"}
  ],
  hinglish: [
    {label:"dil toot gaya",val:"dil toot gaya",h:true},
    {label:"sona",val:"sona",h:true},
    {label:"kal",val:"kal",h:true},
    {label:"bank gaya",val:"bank gaya",h:true},
    {label:"aankhein khul gayin",val:"aankhein khul gayin",h:true},
    {label:"bahut acha",val:"bahut acha",h:true},
    {label:"heartbreak",val:"heartbreak",h:true},
    {label:"sitting idle",val:"sitting idle",h:true}
  ]
};

function buildChips() {
  const c = document.getElementById("quickChips");
  c.innerHTML = "";
  (QUICK_H[inputMode] || QUICK_H.hindi).forEach(q => {
    const b = document.createElement("button");
    b.className = "chip" + (q.h ? " hinglish" : "");
    b.textContent = q.label;
    b.onclick = () => { document.getElementById("searchInp").value = q.val; doSearch(); };
    c.appendChild(b);
  });
}

function doSearch() {
  let q = document.getElementById("searchInp").value.trim();
  if (!q) return;
  if (inputMode === "hinglish") { const m = resolveHinglish(q); if (m) q = m; }
  searchQuery = q; render();
}

function clearAll() {
  document.getElementById("searchInp").value = "";
  searchQuery = ""; activeFilter = null;
  document.querySelectorAll(".fchip").forEach(b => b.classList.remove("active"));
  document.querySelector(".fchip").classList.add("active");
  render();
}

function findBest(q) {
  if (!q) return null;
  let entries = DB;
  if (activeFilter) entries = entries.filter(e => e.type === activeFilter);
  const exact = entries.find(e => e.key === q);
  if (exact) return [exact];
  const qw = new Set(q.split(/\\s+/));
  const scored = entries.map(e => {
    const kw = new Set(e.key.split(/\\s+/));
    const overlap = [...kw].filter(w => qw.has(w)).length;
    return {entry: e, score: overlap};
  }).filter(x => x.score > 0).sort((a, b) => b.score - a.score);
  return scored.length ? scored.map(x => x.entry) : null;
}

function renderCard(e) {
  const meta = TYPE_META[e.type] || {label: e.type, en: e.type};
  const pill = '<span class="type-pill tp-' + e.type + '">' + meta.label + ' / ' + meta.en + '</span>';
  const mhtml = e.meanings.map((m, i) =>
    '<div class="meaning ' + MCLASS[i] + '">' +
    '<div class="mlabel">व्याख्या ' + (i+1) + ' — Interpretation ' + (i+1) + '</div>' +
    '<div class="mhi">' + m.hi + '</div>' +
    '<div class="men">' + m.en + '</div>' +
    '</div>'
  ).join("");
  const ex = e.example ? '<div class="example-tag">' + e.example + '</div>' : "";
  return '<div class="rcard"><div class="rcard-hdr"><span class="sent">' + e.key + '</span>' + pill + '</div><div class="meanings-grid">' + mhtml + '</div>' + ex + '</div>';
}

function render() {
  const out = document.getElementById("mainOut");
  const label = document.getElementById("browseLabel");
  const sstat = document.getElementById("s-filtered");
  let entries = DB;
  if (activeFilter) entries = entries.filter(e => e.type === activeFilter);
  if (searchQuery) {
    const r = findBest(searchQuery);
    if (!r) {
      out.innerHTML = '<div class="notfound"><strong>' + searchQuery + '</strong> not found. Try: <b>कल, सोना, दिल टूट गया</b> or Hinglish: <b>kal, sona, dil toot gaya, heartbreak</b></div>';
      sstat.textContent = 0; label.textContent = "Search results"; return;
    }
    sstat.textContent = r.length;
    label.textContent = 'Search results for "' + searchQuery + '"';
    out.innerHTML = r.map(renderCard).join(""); return;
  }
  sstat.textContent = entries.length;
  label.textContent = activeFilter ? "Browsing: " + (TYPE_META[activeFilter] ? TYPE_META[activeFilter].en : activeFilter) : "Browse all entries";
  const grid = entries.map(e => {
    const meta = TYPE_META[e.type] || {label: e.type, en: e.type};
    return '<div class="browse-card" onclick="sel(\\'' + e.key.replace(/'/g, "\\\\'") + '\\')">' +
      '<div class="bkey">' + e.key + '</div>' +
      '<div class="btype">' + meta.label + ' / ' + meta.en + '</div></div>';
  }).join("");
  out.innerHTML = '<div class="browse-grid">' + grid + '</div>';
}

function sel(key) { document.getElementById("searchInp").value = key; searchQuery = key; render(); }

document.getElementById("s-total").textContent = DB.length;
buildFilters(); buildChips(); render();
document.getElementById("searchInp").addEventListener("keydown", e => { if (e.key === "Enter") { e.preventDefault(); doSearch(); } });
</script>
</body>
</html>"""))

